on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - run: |
          pip install requests
          python .github/workflows/main.py
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: CloudFormation Resource Provider update
          title: CloudFormation Resource Provider update
          delete-branch: true
